### get all assignments from db
GET http://localhost:7800/api/assignments HTTP/1.1


### get assignment by id
GET http://localhost:7800/api/assignments/2 HTTP/1.1


### answer assignment
POST http://localhost:7800/api/assignments/3 HTTP/1.1
Content-Type: application/json

{
    "code": "def sum(a, b): return a + b",
    "user_uuid": "arnel16"
}


### get all answers from db
GET http://localhost:7800/api/answers HTTP/1.1


### grader-api
GET http://localhost:7800/api/grade HTTP/1.1


### check user exists 
GET http://localhost:7800/api/user/f9d15076-bc40-4cdf-874d-af8b259667d4 HTTP/1.1



### update submission
PATCH http://localhost:7800/api/assignments/submissions/1/76027110-d507-4aac-89a6-f6c6b45f5a25 HTTP/1.1
Content-Type: application/json


{
    "grader_feedback": "passes test",
    "status": "processed",
    "correct": true,
    "score": 100
}

### get submission by Id
GET http://localhost:7800/api/assignments/submissions/11


### get all submissions made by user
GET http://localhost:7800/api/assignments/submissions/user/all/arnel10


### test grading
POST http://localhost:7800/api/assignments/grading/1 HTTP/1.1
Content-Type: application/json

{
   "code": "def hello(): return 'Hello'"

}

### get user latest submission
GET http://localhost:7800/api/assignments/submissions/latest-submission/1/arnel27
